export enum OcupacionTrabajador {
  INGENIERO_CIVIL = 'INGENIERO_CIVIL',
  CONTRATISTA = 'CONTRATISTA',
  ALBANIL = 'ALBANIL',
  PLOMERO = 'PLOMERO',
  ELECTRICISTA = 'ELECTRICISTA',
  VIDRIERO = 'VIDRIERO',
  CARPINTERO = 'CARPINTERO',
}
