export enum RolUsuario {
  ADMIN = 'ADMIN',
  GESTOR_PROYECTO = 'GESTOR_PROYECTO',
  INGENIERO = 'INGENIERO',
  ENCARGADO_COMPRAS = 'ENCARGADO_COMPRAS',
  CONTRATISTA = 'CONTRATISTA',
  LECTOR = 'LECTOR',
}
