export const CLIENTE_REPOSITORY = Symbol('CLIENTE_REPOSITORY');
export const PROYECTO_REPOSITORY = Symbol('PROYECTO_REPOSITORY');
export const CRONOGRAMA_REPOSITORY = Symbol('CRONOGRAMA_REPOSITORY');
export const TAREA_REPOSITORY = Symbol('TAREA_REPOSITORY');
export const SEGUIMIENTO_REPOSITORY = Symbol('SEGUIMIENTO_REPOSITORY');
export const CONTRATO_REPOSITORY = Symbol('CONTRATO_REPOSITORY');
export const CONTRATISTA_REPOSITORY = Symbol('CONTRATISTA_REPOSITORY');
export const TRABAJADOR_REPOSITORY = Symbol('TRABAJADOR_REPOSITORY');
export const MATERIAL_REPOSITORY = Symbol('MATERIAL_REPOSITORY');
export const PROVEEDOR_REPOSITORY = Symbol('PROVEEDOR_REPOSITORY');
export const ORDEN_COMPRA_REPOSITORY = Symbol('ORDEN_COMPRA_REPOSITORY');
export const ENTREGA_MATERIAL_REPOSITORY = Symbol(
  'ENTREGA_MATERIAL_REPOSITORY',
);
export const ASIGNACION_TAREA_REPOSITORY = Symbol(
  'ASIGNACION_TAREA_REPOSITORY',
);
export const ASIGNACION_MATERIAL_REPOSITORY = Symbol(
  'ASIGNACION_MATERIAL_REPOSITORY',
);
export const PRONOSTICO_MATERIAL_REPOSITORY = Symbol(
  'PRONOSTICO_MATERIAL_REPOSITORY',
);
export const ALERTA_REPOSITORY = Symbol('ALERTA_REPOSITORY');
export const REPORTE_REPOSITORY = Symbol('REPORTE_REPOSITORY');
export const USUARIO_REPOSITORY = Symbol('USUARIO_REPOSITORY');
