export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CLIENTES: '/clientes',
  PROYECTOS: '/proyectos',
  CRONOGRAMAS: '/cronogramas',
  TAREAS_OBRA_FINA: '/tareas/obra-fina',
  TAREAS_OBRA_BRUTA: '/tareas/obra-bruta',
  SEGUIMIENTOS: '/seguimientos',
  CONTRATOS: '/contratos',
  TRABAJADORES: '/trabajadores',
  ASIGNACIONES_OBRA_BRUTA: '/asignaciones/obra-bruta',
  ASIGNACIONES_OBRA_FINA: '/asignaciones/obra-fina',
  ASIGNACIONES_CONTRATISTA: '/asignaciones/contratista',
  MATERIALES: '/materiales',
  PROVEEDORES: '/proveedores',
  ORDENES_COMPRA: '/ordenes-compra',
  ENTREGAS_MATERIALES: '/entregas-materiales',
  IA_ASIGNACION: '/ia/asignacion-materiales',
  IA_PRONOSTICO: '/ia/pronostico-materiales',
  ALERTAS: '/alertas',
  REPORTES: '/reportes',
} as const;
